#!/bin/sh

set -e

for name in "$@"; do
    (
    cd "$name"
    bin="${name%%-*}"
    docker build -t "$name" .
    [ "$bin" = 'base' ] && exit 0
    container_id="$(docker create $name)"
    docker cp "${container_id}:/build/${bin}" "$name"
    docker rm -v "$container_id"
    echo
    file "$name"
    ls -lah "$name"
    )
done
