#!/bin/sh

set -e

git submodule update --init --recursive

(
    cd "$1"
    bin="${1%%-*}"
    docker build -t "$1" .
    [ "$bin" = 'base' ] && exit 0
    container_id="$(docker create $1)"
    cd src
    name="${1}-git-$(git describe --tags --abbrev=0)-$(git log -1 --pretty=format:'%h')"
    cd -
    docker cp "${container_id}:/build/${bin}" "$name"
    docker rm -v "$container_id"
    echo
    file "$name"
    ls -lah "$name"
)
